4.08.0+rc2+cx+mekh+2
MekhrubonT/ocaml pull request #2
Opened 2019-07-24 10:08 UTC by MekhrubonT

2019-08-02 16:03 UTC, lpw25 requested changes

2019-08-02 16:03 UTC, lpw25 commented on testsuite/tests/typing-equality-exception/test.ml
> +       The first object type has no method f
This message should say "second"

2019-08-02 16:03 UTC, lpw25 commented on testsuite/tests/typing-equality-exception/test.ml
> +       Type 'a is not compatible with type 'b
This message is a bit of a shame. It would be better if we could get it to be:
```ocaml
Type 'a * 'a is not compatible with type 'a * 'b
Type 'a is not compatible with type 'b
```

2019-08-02 16:03 UTC, lpw25 commented on testsuite/tests/typing-equality-exception/test.ml
>  |}];;
This should be "first"

2019-08-02 16:03 UTC, lpw25 commented on testsuite/tests/typing-equality-exception/test.ml
> +       The first is open and second is not
This is back-to-front

2019-08-02 16:03 UTC, lpw25 commented on testsuite/tests/typing-equality-exception/test.ml
>  |}];;
back-to-front

2019-08-02 16:03 UTC, lpw25 commented on typing/errortrace.ml
> +module Unification_trace = struct
I think that just `Unification` would be fine since "trace" is already in the `Errortrace` name

2019-08-02 16:03 UTC, lpw25 commented on typing/errortrace.ml
> +module Trace = Unification_trace
If this alias is still needed it should probably go back in `ctype.ml`

2019-08-02 16:03 UTC, lpw25 commented on typing/errortrace.ml
> +exception Unify = Trace.Unify
I'd probably leave the exceptions in `ctype.ml`

2019-08-02 16:03 UTC, lpw25 commented on typing/includecore.ml
> +         pr "is not compatible with type"
I think that "is not equal to type" may be better for all the equality messages.

2019-08-02 16:03 UTC, lpw25 commented on typing/includecore.ml
> +         | exception Equality trace -> Some (Type (env, trace)))
In the compiler I'd expect `begin ... end` rather than `( ... )` around an inner match case like this.

In Jane Street code it's normally `( ... )` these days because that's what the `ocamlformat` tool does.

2019-08-02 16:13 UTC, MekhrubonT reviewed
qwe

2019-08-05 08:49 UTC, MekhrubonT commented on testsuite/tests/typing-equality-exception/test.ml
> +       Type 'a is not compatible with type 'b
It is already fixed in another branch(The branch of pull request to trunk)

2019-08-20 12:12 UTC, closed without merging